### ISSUE TITLE
pna_code location

### ISSUE THREAD

**Issue by cmahlen** [practical-neuroimaging/pna2015#11]
I'm not sure if anyone is still maintaining this, but thank you in advance if you are, both for the great course and if you can help me with this issue. On day6's `regression.ipynb`, there is an early reference to a directory called `pna_code` that contains functions like `spm_func` and `stimuli` which seem to be used for the rest of the notebook. I couldn't find this directory anywhere. Does anyone know where it is?

**Comment by matthew-brett** [comment]
Well - kinda!   There's a later version of the course that is better maintained over at https://textbook.nipraxis.org . For that particular problem, we're referring to the results from doing <https://github.com/practical-neuroimaging/pna2015/blob/master/day4/git_101.ipynb> and <https://github.com/practical-neuroimaging/pna2015/blob/master/day4/first_statistics.ipynb>.

**Comment by cmahlen** [comment]
Awesome, thank you!
